 using Npgsql;
using System;

namespace testepostgres
{
    class Program
    {
        static void Main(string[] args)
        {
            var order = new Order(5, 1.000, 2000, 7);
            InserirPedido(order);
            Console.WriteLine($"Pedido adicionado com sucesso. Latitude {order.Latitude} \n Longitude {order.Longitude} \n Status {order.Status} ");
            Console.ReadKey();

        }

        static void InserirPedido (Order order)
        {
            var cs = "Host=localhost;Username=postgres;Password=1910710;Database=teste";
            var con = new NpgsqlConnection(cs);
            con.Open();

            var sql = "INSERT INTO tb_order(latitude, longitude, status) VALUES(@latitude, @longitude, @status)";

            var cmd = new NpgsqlCommand(sql, con);
            cmd.Parameters.AddWithValue("latitude", order.Latitude);
            cmd.Parameters.AddWithValue("longitude", order.Longitude);
            cmd.Parameters.AddWithValue("status", order.Status);
            cmd.Prepare();
            cmd.ExecuteNonQuery();
            con.Close();

        }
    }
}


//create table tb_order(
//    id int8 generated by default as identity,
//    latitude float8,
//    longitude float8,
//    status int4,
//    primary key (id)
//);



//var cs = "Host=localhost;Username=postgres;Password=1910710;Database=teste";

//var con = new NpgsqlConnection(cs);
//con.Open();

//            var sql = "SELECT version()";

//var cmd = new NpgsqlCommand(sql, con);

//var version = cmd.ExecuteScalar().ToString();
//Console.WriteLine($"PostgreSQL version: {version}");
